# Project name and version
name: 'snowflake_fivetran_vhol'
version: '1.7.14'
config-version: 2

# Profile configuration
profile: 'default'

# File path configurations
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target directory configuration
target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# Configuring models
# (Example of configuring materialization)
# models:
#   snowflake_fivetran_vhol:
#       my_model:
#           materialized: view

# Variables
vars:
    google_ads_schema: 'GOOGLE_SHEETS'
    google_ads_database: 'DATA'
    google_ads_table: 'JOB'
